# Generated by Django 2.1.7 on 2019-04-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField()),
                ('ModifiedOn', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=100)),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=50)),
                ('Purpose', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=5000)),
                ('Categories', models.ManyToManyField(blank=True, to='cc.Category')),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=50)),
                ('SystemDefined', models.BooleanField(default=True)),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.AddField(
            model_name='community',
            name='Roles',
            field=models.ManyToManyField(blank=True, to='cc.Role'),
        ),
    ]
