# Generated by Django 2.1.8 on 2019-05-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Workflow',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cc.Workflow'),
        ),
    ]
