# Generated by Django 2.1.7 on 2019-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='AvailableTill',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
