# Generated by Django 2.1.8 on 2019-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Type',
            field=models.IntegerField(choices=[(0, 'NotSpecified'), (1, 'Admin'), (2, 'Member')], default=2),
            preserve_default=False,
        ),
    ]
