# Generated by Django 2.1.8 on 2019-04-22 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='IsCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='execution',
            name='ExecutedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executiondata',
            name='DataGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cc.ExecutionData'),
        ),
    ]
