# Generated by Django 2.1.7 on 2019-04-11 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEnumeration',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=50)),
                ('Value', jsonfield.fields.JSONField(default='{}')),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.IntegerField(choices=[(0, 'Error'), (1, 'Integer'), (2, 'String'), (3, 'Boolean'), (4, 'Color'), (5, 'DayOfWeek'), (6, 'Date'), (7, 'Time'), (8, 'Empty'), (9, 'DateTime')])),
                ('Treasure', models.BooleanField(default=False)),
                ('Enumerations', models.ManyToManyField(blank=True, to='cc.DataEnumeration')),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=50)),
                ('Fields', models.ManyToManyField(blank=True, to='cc.DataField')),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='ExecutionData',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Value', jsonfield.fields.JSONField(default='{}')),
                ('DataGroup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cc.ExecutionData')),
                ('Field', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cc.DataField')),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Banned', models.BooleanField(default=False)),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Community')),
                ('Roles', models.ManyToManyField(blank=True, to='cc.Role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=5000)),
                ('Available', models.BooleanField(default=False)),
                ('AvailableTill', models.DateField(blank=True)),
                ('AvailableTimes', models.IntegerField(default=0)),
                ('InputFields', models.ManyToManyField(blank=True, related_name='InputFields', to='cc.DataField')),
                ('OutputFields', models.ManyToManyField(blank=True, related_name='OutputFields', to='cc.DataField')),
                ('Predecessors', models.ManyToManyField(blank=True, to='cc.Task')),
                ('Roles', models.ManyToManyField(blank=True, to='cc.Role')),
                ('Users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.BaseModel')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=5000)),
                ('Roles', models.ManyToManyField(blank=True, to='cc.Role')),
                ('Tasks', models.ManyToManyField(blank=True, to='cc.Task')),
                ('Users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cc.basemodel',),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execution',
            name='Data',
            field=models.ManyToManyField(blank=True, to='cc.ExecutionData'),
        ),
        migrations.AddField(
            model_name='execution',
            name='Task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cc.Task'),
        ),
        migrations.AddField(
            model_name='execution',
            name='User',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
