# Generated by Django 2.1.8 on 2019-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20190527_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='AvailableTimes',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
