# Generated by Django 2.1.7 on 2019-05-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20190527_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='Task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cc.Task'),
        ),
    ]
