# Generated by Django 2.1.8 on 2019-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20190528_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='AvailableTimes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
