# Generated by Django 2.1.8 on 2019-05-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20190428_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Community',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Roles',
        ),
        migrations.RemoveField(
            model_name='member',
            name='User',
        ),
        migrations.RemoveField(
            model_name='member',
            name='basemodel_ptr',
        ),
        migrations.AddField(
            model_name='datatype',
            name='Community_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cc.Community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='Categories',
            field=models.ManyToManyField(blank=True, related_name='Categories', to='cc.Category'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
