# Generated by Django 2.1.8 on 2019-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_auto_20190514_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatype',
            old_name='Community_id',
            new_name='Community',
        ),
        migrations.AlterField(
            model_name='datafield',
            name='Type',
            field=models.IntegerField(choices=[(0, 'NotSpecified'), (1, 'Integer'), (2, 'String'), (3, 'Boolean'), (4, 'DateTime'), (5, 'GeoLocation'), (6, 'Relation'), (7, 'User'), (8, 'Image')]),
        ),
    ]
