version: "3"

services:
  api:
    build: ./api
    command: manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"

  web:
    build: ./ui
    restart: always
    command: sh -c "npm run serve"
    volumes:
      - ./ui:/ui
    ports:
      - "8080:8080" 
