version: "3"

services:
  api:
    build: ./api
    command: gunicorn app.wsgi
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
  
  nginx:
    build: ./nginx
    depends_on: 
      - api
    command: nginx -g 'daemon off;'
    ports: 
      - "80:80"
    volumes: 
      - ./api/static:/api/static