version: "3"

services:
  api:
    build: ./api
    command: gunicorn -c gunicorn.conf app.wsgi
    restart: always
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"

  web:
    build: ./ui
    environment:
      - VUE_APP_BASE_URL=http://api.communal-cloud.com/
    restart: always
    command: sh -c "npm run serve"
    volumes:
      - ./ui:/ui
    ports:
      - "8080:8080"
  
  nginx:
    build: ./nginx
    restart: always
    depends_on: 
      - api
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes: 
      - ./api/static:/api/static/

